name: nukeCache
description: "Small Win_utility tool to ease bash and terminal commands"
publish_to: 'none'
version: 0.3.3

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6

  device_info_plus: ^9.1.2
  fluent_ui: ^4.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  gap: ^3.0.1
  geekyants_flutter_gauges: ^1.0.3
  path_provider: ^2.1.2
  win32: ^5.2.0
  system_info3: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
